apiVersion: v1
kind: ConfigMap
metadata:
  name: my-flomo-server-secret
  labels:
    app: my-flomo-server
data:
  HOST: localhost
  DSN: /app/data/my-flomo.db
  JWT_KEY: YOUR_JWT_KEY
  SMTP_HOST: smtp-mail.outlook.com
  SMTP_PORT: "587"
  SMTP_USERNAME: YOUR_EMAIL
  SMTP_PASSWORD: YOUR_PASSWORD
  SMTP_SUBJECT: My Flomo 每日回顾
